# environment.yml

name: mlops_env
channels:
  - conda-forge
dependencies:
  - python=3.13.3
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - hyperopt
  - xgboost
  - jupyterlab
  - black
  - flake8
  - mlflow
